apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: deaconbluepipelinesjavascriptdocker #weatherdotnetdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deaconbluepipelinesjavascriptdocker #weatherdotnetdocker 
    spec:
      containers:
        - name: deaconbluepipelinesjavascriptdocker #weatherdotnetdocker 
          image: az0402acr.azurecr.io/deaconbluepipelinesjavascriptdocker #weatherdotnetdocker
          ports:
          - containerPort: 5000