apiVersion: v1
kind: Service
metadata:
    name: deaconbluepipelinesjavascriptdocker #weatherdotnetdocker
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: deaconbluepipelinesjavascriptdocker #weatherdotnetdocker