apiVersion: v1
kind: Service
metadata:
    name: deaconbluepipelinesjavascriptdocker #weatherdotnetdocker
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: deaconbluepipelinesjavascriptdocker #weatherdotnetdocker